#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip2 install --no-cache-dir -U pip
pip2 install --no-cache-dir -r ${OPENSHIFT_REPO_DIR}test_ddf_project/requirements.txt
if [ -f ${OPENSHIFT_DATA_DIR}sentry ]; then
    pip2 --no-cache-dir install raven
fi

pushd ${OPENSHIFT_REPO_DIR}test_ddf_project
    ./manage.py migrate
    mkdir -p wsgi
    ./manage.py collectstatic --noinput
popd

mkdir -p ${OPENSHIFT_DATA_DIR}media
mkdir -p ${OPENSHIFT_REPO_DIR}wsgi/static/media
ln -sf ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}wsgi/static/media
